[package]
name = "rs"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]

[dependencies]
failure = "0.1.2"
rustyline = "1.0.0"
regex = "1.0.2"
lazy_static = "1.1.0"
indextree = "2.1.0"
log = "0.4.4"
pretty_env_logger = "0.2.4"
debug_stub_derive = "0.3.0"
time = "0.1.40"
