step0_repl:
	cargo build
step1_read_print:
	cargo build
step2_eval:
	cargo build
step3_env:
	cargo build
step4_if_fn_do:
	cargo build
step5_tco:
	cargo build
step6_file:
	cargo build
step7_quote:
	cargo build
